### ISSUE TITLE
Facing issue when using export module

### ISSUE THREAD

**Issue by srini26juin90** [pipesort/lambda-pdf#1]
i am trying to use the async function and return the data in the form of post. But facing difficulties to do it. can you help me out

**Comment by ghost** [comment]
@srini26juin90 Hi, your question is little unclear. I would suggest you to write a simple async function and try returning something hardcoded or existing file before you try this pdf generation. If you run into error when creating such a bare minimum lambda function please raise a question in Stackoverflow

**Comment by srini26juin90** [comment]
I am new to Nodejs. I want to convert the screenshot image to base64 and i achieved it through
`const pdf = await page.screenshot({ encoding: "base64" })`
I am gonna run the async function to take screenshot inside a for loop and save the resulting data inside and array, finally using s3.putobject to save the data in s3
My api function
`app.post('/screenshot', function(req, res) {
     forLoop() {
     Trying to use the async func here 
     }
})`

**Comment by ghost** [comment]
@srini26juin90 I think you should post the question to stackoverflow with little more details and code.
